# Generated by Django 5.1.1 on 2025-03-09 14:30

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('tipo_evento', models.CharField(choices=[('Clase', 'Clase'), ('Examen', 'Examen'), ('Reunión', 'Reunión'), ('Otro', 'Otro')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ejemplo: 1° de Secundaria', max_length=50)),
                ('descripcion', models.TextField(blank=True, default='Descripción no disponible', help_text='Descripción opcional del grado', null=True)),
                ('imagen', models.URLField(blank=True, help_text='Enlace a una imagen representativa del grado', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Tema')),
                ('descripcion', ckeditor.fields.RichTextField(blank=True, help_text='Descripción detallada del tema con formato enriquecido', verbose_name='Descripción')),
                ('numero', models.PositiveIntegerField(help_text='Número del tema dentro de la unidad', verbose_name='Número')),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='AlumnoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='alumnos/')),
                ('foto_dni', models.ImageField(blank=True, null=True, upload_to='documentos/dni/')),
                ('partida_nacimiento', models.ImageField(blank=True, null=True, upload_to='documentos/partidas/')),
                ('ficha_matricula', models.FileField(blank=True, null=True, upload_to='documentos/matriculas/')),
                ('codigo_estudiante', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('estado_academico', models.CharField(choices=[('Regular', 'Regular'), ('Condicional', 'Condicional'), ('Retirado', 'Retirado')], default='Regular', max_length=20)),
                ('nombre_padre', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_padre', models.CharField(blank=True, max_length=15, null=True)),
                ('nombre_madre', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_madre', models.CharField(blank=True, max_length=15, null=True)),
                ('nombre_tutor', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_tutor', models.CharField(blank=True, max_length=15, null=True)),
                ('tipo_sangre', models.CharField(blank=True, max_length=5, null=True)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('enfermedades', models.TextField(blank=True, null=True)),
                ('seguro_medico', models.CharField(blank=True, max_length=100, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=50, null=True)),
                ('idiomas', models.CharField(blank=True, help_text='Ejemplo: Español, Inglés, Francés', max_length=100, null=True)),
                ('salida_autorizada', models.BooleanField(default=True, help_text='¿Puede salir solo después de clases?')),
                ('restricciones_legales', models.TextField(blank=True, help_text='Ejemplo: Orden judicial, tutoría legal', null=True)),
                ('alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestion_alumnos.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Comportamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('observacion', models.TextField()),
                ('calificacion', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Deficiente', 'Deficiente')], max_length=20)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_alumnos.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='CursoAsignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_alumnos.curso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_alumnos.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(default=django.utils.timezone.now)),
                ('tipo_examen', models.CharField(choices=[('Parcial', 'Parcial'), ('Final', 'Final'), ('Práctico', 'Práctico'), ('Otro', 'Otro')], default='Parcial', max_length=50)),
                ('curso_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_alumnos.cursoasignado')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_alumnos.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comentarios', models.TextField(blank=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_alumnos.alumno')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_alumnos.examen')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='gestion_alumnos.grado'),
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.TextField(blank=True, default='Descripción no disponible', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20)),
                ('años_duracion', models.PositiveIntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='niveles/')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='grado',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grados', to='gestion_alumnos.nivel'),
        ),
        migrations.CreateModel(
            name='Practica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('curso_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_alumnos.cursoasignado')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_alumnos.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionPractica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comentarios', models.TextField(blank=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_alumnos.alumno')),
                ('practica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_alumnos.practica')),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=5)),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_alumnos.grado')),
            ],
        ),
        migrations.AddField(
            model_name='cursoasignado',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_alumnos.seccion'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_alumnos.seccion'),
        ),
        migrations.CreateModel(
            name='RecursoDidactico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción breve del recurso')),
                ('tipo', models.CharField(choices=[('Documento', 'Documento'), ('Video', 'Video'), ('Enlace', 'Enlace'), ('Otro', 'Otro')], default='Documento', max_length=50)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='recursos/')),
                ('enlace', models.URLField(blank=True, help_text='Enlace a un recurso externo', null=True)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='gestion_alumnos.tema')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_entrega', models.DateField()),
                ('hora_entrega', models.TimeField(default=django.utils.timezone.now)),
                ('tipo_trabajo', models.CharField(choices=[('Ensayo', 'Ensayo'), ('Investigación', 'Investigación'), ('Ejercicios', 'Ejercicios'), ('Proyecto', 'Proyecto'), ('Otro', 'Otro')], default='Otro', max_length=50)),
                ('es_obligatorio', models.BooleanField(default=True)),
                ('curso_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_alumnos.cursoasignado')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_alumnos.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, help_text='Ingrese una nota entre 0 y 20.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('comentarios', models.TextField(blank=True, verbose_name='Comentarios del Docente')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Revisado', 'Revisado'), ('Aprobado', 'Aprobado')], default='Pendiente', max_length=10)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='gestion_alumnos.alumno')),
                ('curso_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='gestion_alumnos.cursoasignado')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='gestion_alumnos.trabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', ckeditor.fields.RichTextField(blank=True, help_text='Descripción breve de la unidad')),
                ('numero', models.PositiveIntegerField(help_text='Número de la unidad dentro del curso')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='gestion_alumnos.curso')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.AddField(
            model_name='tema',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='gestion_alumnos.unidad', verbose_name='Unidad'),
        ),
        migrations.CreateModel(
            name='Planificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('objetivos', models.TextField(help_text='Objetivos de la planificación')),
                ('actividades', models.TextField(help_text='Descripción de las actividades a realizar')),
                ('evaluacion', models.TextField(help_text='Criterios de evaluación')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones', to='gestion_alumnos.unidad')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('aula', models.CharField(blank=True, max_length=50, null=True)),
                ('curso_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_alumnos.cursoasignado')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_alumnos.docente')),
            ],
            options={
                'unique_together': {('docente', 'dia', 'hora_inicio', 'hora_fin')},
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.TimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('Presente', 'Presente'), ('Tarde', 'Tarde'), ('Ausente', 'Ausente')], default='Presente', max_length=10)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='gestion_alumnos.alumno')),
                ('curso_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='gestion_alumnos.cursoasignado')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='gestion_alumnos.periodo')),
            ],
            options={
                'unique_together': {('alumno', 'curso_asignado', 'fecha')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='tema',
            unique_together={('unidad', 'numero')},
        ),
    ]
