# Generated by Django 5.1.1 on 2025-03-15 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_entrega', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='gestion_alumnos.docente')),
            ],
        ),
    ]
